### ISSUE TITLE
meta: OpenJS interviews

### ISSUE THREAD

**Issue by boneskull** [mochajs/admin#1]
The OpenJS marketing dept wants to interview  project maintainers to get a better feel for how to promote the projects. 

Who might be interested? cc @mochajs/core @jorydotcom

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by boneskull** [comment]
@jorydotcom I'm fine w/ talking to whoever.

**Comment by craigtaub** [comment]
Im happy talking to whoever as well (not an OS expert but am pretty familiar with our processes at mocha).

**Comment by jorydotcom** [comment]
@craigtaub you don't have to be! just be able to talk, in somewhat lay-persons terms, about what's new in the project and why its exciting :D 

All: please share your email with me so I can intro you to the marketing folks! And related, if you want to get updates from the OpenJS Foundation (which will include regular dispatches from yours truly) please [sign-up here](https://lists.openjsf.org/g/main).

**Comment by craigtaub** [comment]
👍. My email is the one on my GH (craigtaub@gmail.com)

**Comment by boneskull** [comment]
same, you have mine, boneskull@boneskull.com

**Comment by Bamieh** [comment]
Both Chris and Craig are the experts here but I have no problem helping out if needed. ahmadbamieh@gmail.com

**Comment by outsideris** [comment]
My English is not fluent. But I am available if you need. outsideris@gmail.com

**Comment by boneskull** [comment]
@jorydotcom 	FWIW, I haven't been contacted about this yet.

**Comment by jorydotcom** [comment]
I heard through the grapevine that the person who was championing this is no longer with the LF. I'll see if the new marketing person plans to pick this back up, but in the interim will close this issue. Thanks everyone for being game to do this. Hope we can get back to it soon.
