### ISSUE TITLE
Requesting owner access to swap the CLA bot

### ISSUE THREAD

**Issue by brianwarner** [mochajs/admin#14]
Hi, the existing JSF CLA bot is no longer working. I can replace it with EasyCLA, but will need owner access to enable the new app and disable the existing webhooks. Thank you!

**Comment by outsideris** [comment]
@boneskull have the permission.

**Comment by juergba** [comment]
@brianwarner thank you for your request.

What do you you need exactly?
Should we send you a member invitation?
When and how long will you need this permission?

The signed CLA history data will be lost, right?

**Comment by juergba** [comment]
We have a `JSFOwner` member with owner access, which has handled the CLA assist in the past.
What is the purpose of this member? Why can't you use this one for EasyCLA?

@jorydotcom the communication of this CLA bot migration is weird.

**Comment by outsideris** [comment]
Any update? 
Now, we don't have any CLA assist.

**Comment by brianwarner** [comment]
Hi @outsideris, sorry for the delay, if I can be added as an owner on the org, I can configure the CLA. It just takes a few minutes, usually.

**Comment by juergba** [comment]
@brianwarner I sent an owner invitation to you.

I guess we can remove the existing `JSFOwner` and your account after the configuration has been done?

**Comment by outsideris** [comment]
Now, we have the CLA again. 

>  guess we can remove the existing JSFOwner and your account after the configuration has been done?

@brianwarner Please check this.

**Comment by brianwarner** [comment]
Yep! You're good to go.

**Comment by outsideris** [comment]
@juergba

**Comment by outsideris** [comment]
Thank you @brianwarner

**Comment by juergba** [comment]
@brianwarner thank you
