### ISSUE TITLE
Mocha + Tidelift

### ISSUE THREAD

**Issue by phated** [mochajs/admin#6]
Hey Mocha team!

I had a great chat with @boneskull at the OpenJS Collaborators Summit about open source, funding (see #5), and Tidelift—where I just started working.

I’ve been looking through our list of projects that have funding available and noticed [Mocha has almost $700 per month](https://tidelift.com/lifter/search/npm/mocha) that can be claimed by your core contributors. We’d love to get some of the team signed up so we can start paying you this money. It can be claimed by one maintainer that wants to be responsible for Tidelift tasks or you can split it amongst multiple maintainers. If you are looking to split it up, I highly recommend checking out [pytest’s Tidelift guidelines for their maintainers](https://github.com/pytest-dev/pytest/blob/master/TIDELIFT.rst).

The high-level overview of Tidelift is that we sell a “managed open source” subscription to companies and pay that money out to maintainers. We use their dependency trees to determine which packages are depended upon and, therefore, should get the funds. You can read more about Tidelift’s subscription service [on our site](https://tidelift.com/subscription).

The tasks we ask you to perform are things that most maintainers already do (such as provide release notes, validate the license of a package, and monitor and alert for security vulnerabilities), but you can find the specific details in [this blog post](https://blog.tidelift.com/how-to-start-earning-money-for-your-open-source-project-with-tidelift) by @kszu.

Please let me know what you think! I’m happy to answer any other questions you might have. :smile:

Thanks for all your hard work,
-Blaine

**Comment by Munter** [comment]
I think our current build and hosting solution is running us at a loss because they haven't started billing us for the over-use yet. Would be nice if I could move us into a paid tier and have the hosting covered by something like Tidelift

**Comment by boneskull** [comment]
@Munter tbh we don't need it, we have kind of pile of $ atm

**Comment by boneskull** [comment]
@Munter we should extract Mocha's stuff from yours though

**Comment by phated** [comment]
@Munter I reached out by email. Did you receive it?
