### ISSUE TITLE
[Info] OpenJS Conference & Collab Summit FYIs for Project Communities

### ISSUE THREAD

**Issue by jorydotcom** [mochajs/admin#9]
Hi Mocha Community 🤗

I've been asked to help make sure that all the OpenJS Foundation project communities are aware that the deadline for our [OpenJS Conference Call for Proposals](https://events.linuxfoundation.org/openjs-world/program/cfp/) has been extended through Feb. 28. Previously, this event was called 'Node + JS Interactive' and it leaned heavily toward Node.js. We're hoping to have a wider range of sessions about all the OpenJS Foundation projects, so we'd love to see presentations about Mocha!

I also wanted to make sure you're aware of the Collaborator's Summit, an event focused on project maintainers, collaborators & contributors. The goal for the collab summit is to provide opportunities for face-to-face working sessions within a single project or across multiple projects. So if you wanted to get your core team together you could do that, or if you want to have a session for new contributors to your project, or if you wanted to work across multiple OpenJS Foundation projects on issues like accessibility, privacy, security, modules, etc. you could do that too. **If you're interested in securing session space at the collab summit, please ping me here, reach out on slack or twitter, or open an issue on the [/summit](https://github.com/openjs-foundation/summit) repo.** 

The OpenJS World conference is June 23-24 and Collaborator's Summit is June 25-26 in Austin, TX. These are ticketed events, but **members of OpenJS Foundation project communities are eligible for [Travel Fund](https://github.com/openjs-foundation/cross-project-council/blob/master/project-resources/MEMBER_TRAVEL_FUND.md) assistance.** If you have questions or would like to find out more, please chime in on our /summit repo. 

as always, let me know how I can help <3
Jory Burson
OpenJS Foundation Community Manager

**Comment by boneskull** [comment]
Update: these conferences are now virtual.

I haven't been following what's happening with the summit, but if we have some interest I'd like to do a session.

**Comment by craigtaub** [comment]
@boneskull I was planning to start working on an "under-the-hood of test runners" talk/presentation/blog which I would focus on Mocha's mechanics. Having a more in-depth understanding could help people contribute faster. Let me know what you think

**Comment by boneskull** [comment]
go for it! that’d be great. would that be something you’d want to do at the summit?

**Comment by craigtaub** [comment]
@boneskull Im going to start putting something together and I will let you know if it will be ready for the summit. I can't offer any guarantees im afraid and I might miss the boat on this one.

**Comment by boneskull** [comment]
Ref: https://github.com/openjs-foundation/summit/issues/284

**Comment by craigtaub** [comment]
@boneskull id like to join that meeting, in UK so UTC+1. 

Would like to suggest a meetup before then aswell, as we havn't done one before (or in a long time) and would be gd to have a chat just us away from OpenJS summit.
